### ISSUE TITLE
Open VPN

### ISSUE THREAD

**Issue by dali99** [LudicLinux/LudicLinux.github.io#1]
> So if your router assigns IPs in 192.168.0.x then you’ll want this line to be:
> `server-bridge 192.168.1.254 255.255.255.0 192.168.1.100 192.168.1.200`

I think this is supposed to say
`server-bridge 192.168.0.254 255.255.255.0 192.168.0.100 192.168.0.200`

**Comment by uoou** [comment]
Thanks, you're quite right. I'll edit that now.
