### ISSUE TITLE
text invisible on some systems

### ISSUE THREAD

**Issue by cprn** [LudicLinux/LudicLinux.github.io#2]
Your website's CSS assumes font and background theme to be _black-on-white_ by default. Please, consider specifying font and background colour for every style as modern browsers often derive colours from system theme or provide an option to set them manually (e.g. Firefox: _Preferences > Content > Colours..._) rendering your website unreadable in case of _white-on-black_ defaults.

Another solution would be to specify neither font or background colours letting the browser to use the user's preference or to prepare several website themes and save the user's choice in a cookie.

**Comment by uoou** [comment]
Sorry for delay, should be fixed (I've specified bg colour).

**Comment by cprn** [comment]
Works great now. Thanks!
